port: 8084
devMode: true
status:
  url: ws://localhost:8082/client/ws/status
speech:
  url: ws://localhost:8082/client/ws/speech
joiner:
  url: http://localhost:8081/invnorm_num
punctuator:
  url: http://localhost:8083/punctuation
redis:
  url: redis://localhost:6379/0
  encryptionKey: 01K6CZRXNCNZZ1HQHMVGGJAD1601K6CZ
  ttl: 10m

logger:
  level: debug
  out: console
