port: 8083
status:
  url: ws://localhost:8082/client/ws/status
speech:
  url: ws://localhost:8082/client/ws/speech  
joiner:
  url: http://localhost:3003/invnorm_num

logger:
    level: DEBUG 
    out: console 